In [1]:
import pandas as pd
import numpy as np
from datetime import date
import holidays
import time

In [2]:
def Col_rename(df):
    for i in list(df.columns):
        if i in ['starttime','started_at','Start Time']:
            df.rename({i:'start_time'}, axis=1, inplace = True)
        if i in ['member_casual','User Type','usertype']:
            df.rename({i: 'user_type'}, axis =1, inplace = True)
        if i in ['tripduration' , 'Trip Duration']:
            df.rename({i: 'duration'}, axis =1, inplace = True)
        if i in ['stoptime'  , 'Stop Time'  ,'ended_at']:
            df.rename({i: 'end_time'}, axis =1, inplace = True)
        if i in ['start station id',  'Start Station ID' ]:
            df.rename({i: 'start_station_id'}, axis =1, inplace = True)
        if i in ['start station name' , 'Start Station Name' ]:
            df.rename({i: 'start_station_name'}, axis =1, inplace = True)
        if i in ['start station latitude' , 'Start Station Latitude' ]:
            df.rename({i: 'start_lat'}, axis =1, inplace = True)
        if i in ['start station longitude', 'Start Station Longitude' ]:
            df.rename({i: 'start_lng'}, axis =1, inplace = True)
        if i in ['end station id' , 'End Station ID' ]:
            df.rename({i: 'end_station_id'}, axis =1, inplace = True)
        if i in ['end station name' ,'End Station Name']:
            df.rename({i: 'end_station_name'}, axis =1, inplace = True)
        if i in ['end station latitude'  ,'End Station Latitude']:
            df.rename({i: 'end_lat'}, axis =1, inplace = True)
        if i in ['end station longitude', 'End Station Longitude']:
            df.rename({i: 'end_lng'}, axis =1, inplace = True)

In [3]:
def Col_to_dt(df):
    df[["start_time", "end_time"]] = df[["start_time", "end_time"]].apply(pd.to_datetime)

In [43]:
df = pd.read_csv("C:\\Users\\Francesco\\Desktop\\NYCDSA\\Capstone file\\CitiBikeDataNYCzipped\\201902-citibike-tripdata.csv")

In [44]:
Col_rename(df)
Col_to_dt(df)

In [72]:
df["day_type"] = df["end_time"].dt.weekday
df['day_type'] = np.where(df['day_type'] > 4, 'Weekend','Weekday')

In [71]:
df['day_type'].value_counts()

Holidays    943744
Name: day_type, dtype: int64

In [ ]:
year =

In [73]:
us_holidays = holidays.US()
for x in df.end_time:
    if x in us_holidays:
        df['day_type'] = 'Holidays'
    else:
        df["day_type"] = df["end_time"].dt.weekday
        df['day_type'] = np.where(df['day_type'] > 4, 'Weekend','Weekday')

KeyboardInterrupt:

In [40]:
us_holidays = holidays.US()
for x in df.end_time:
    if x in us_holidays:
        df['day_type'] = 'Holidays'
    elif df[["day_type"]] < 5:
        df['day_type'] = 'Weekday'
    else:
        df['day_type'] = 'Weekend'

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

,duration,start_time,end_time,start_station_id,start_station_name,start_lat,start_lng,end_station_id,end_station_name,end_lat,end_lng,bikeid,user_type,birth year,gender,day_type
0,219,2019-02-01 00:00:06.257,2019-02-01 00:03:46.109,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,1,Weekday
1,143,2019-02-01 00:00:28.032,2019-02-01 00:02:51.746,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,1,Weekday
2,296,2019-02-01 00:01:13.987,2019-02-01 00:06:10.734,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,1,Weekday
3,478,2019-02-01 00:01:14.152,2019-02-01 00:09:12.787,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,2,Weekday
4,225,2019-02-01 00:01:49.341,2019-02-01 00:05:34.498,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,1,Weekday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,630,2019-02-04 14:28:14.866,2019-02-04 14:38:45.833,496.0,E 16 St & 5 Ave,40.737262,-73.992390,3656.0,E 2 St & Avenue A,40.723077,-73.985836,27574,Subscriber,1995,1,Weekday
99996,1240,2019-02-04 14:28:19.783,2019-02-04 14:48:59.858,128.0,MacDougal St & Prince St,40.727103,-74.002971,387.0,Centre St & Chambers St,40.712733,-74.004607,31586,Customer,1969,0,Weekday
99997,381,2019-02-04 14:28:17.503,2019-02-04 14:34:38.808,402.0,Broadway & E 22 St,40.740343,-73.989551,174.0,E 25 St & 1 Ave,40.738177,-73.977387,34035,Subscriber,1977,2,Weekday
99998,12996,2019-02-04 14:28:22.409,2019-02-04 18:04:59.118,3308.0,Kane St & Clinton St,40.686176,-73.996453,3581.0,Underhill Ave & Lincoln Pl,40.674012,-73.967146,34734,Subscriber,1992,1,Weekday
99999,789,2019-02-04 14:28:20.200,2019-02-04 14:41:29.738,241.0,DeKalb Ave & S Portland Ave,40.689810,-73.974931,399.0,Lafayette Ave & St James Pl,40.688515,-73.964763,33895,Subscriber,1981,1,Weekday

In [30]:
df.day_type.value_counts()

Weekday    943744
Name: day_type, dtype: int64

In [25]:
df[['end_time']][:20].weekday()

AttributeError: 'DataFrame' object has no attribute 'weekday'